name: Deploy DLT Pipeline to Databricks

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Databricks CLI v1
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash

    - name: Deploy DLT Pipeline
      run: |
        databricks pipelines create --json '@dlt_pipeline_config.json' || \
        databricks pipelines update --json '@dlt_pipeline_config.json'

