name: Deploy DLT Pipeline to Databricks

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install New Databricks CLI
      run: |
        pip install --upgrade pip
        pip install databricks-cli --upgrade

    - name: Deploy DLT Pipeline
      run: |
        databricks pipelines create --json-file dlt_pipeline_config.json || \
        databricks pipelines edit --json-file dlt_pipeline_config.json
